/**
 * Documentation Routes
 * 
 * Auto-generated documentation API endpoints for the ProjectWorkflow component.
 * These endpoints provide real-time information about:
 * - Database tables and schemas
 * - API routes and endpoints
 * - Data flows and relationships
 * - Module implementation status
 * 
 * All data is dynamically generated by introspecting the actual system.
 * 
 * @created 2026-01-30
 */

const express = require('express');
const router = express.Router();
const DocumentationService = require('../services/DocumentationService');
const logger = require('../utils/logger');

/**
 * GET /api/documentation/overview
 * Get complete system overview including tables, routes, and data flows
 */
router.get('/overview', async (req, res) => {
  try {
    const overview = await DocumentationService.getSystemOverview();
    res.json(overview);
  } catch (error) {
    logger.error('Error getting system overview:', error);
    res.status(500).json({
      success: false,
      error: 'Failed to get system overview',
      message: error.message
    });
  }
});

/**
 * GET /api/documentation/tables
 * Get all database tables with row counts and categories
 */
router.get('/tables', async (req, res) => {
  try {
    const tables = await DocumentationService.getDatabaseTables();
    res.json(tables);
  } catch (error) {
    logger.error('Error getting database tables:', error);
    res.status(500).json({
      success: false,
      error: 'Failed to get database tables',
      message: error.message
    });
  }
});

/**
 * GET /api/documentation/tables/:tableName
 * Get detailed schema for a specific table
 */
router.get('/tables/:tableName', async (req, res) => {
  try {
    const { tableName } = req.params;
    const schema = await DocumentationService.getTableSchema(tableName);
    res.json(schema);
  } catch (error) {
    logger.error(`Error getting schema for table ${req.params.tableName}:`, error);
    res.status(500).json({
      success: false,
      error: 'Failed to get table schema',
      message: error.message
    });
  }
});

/**
 * GET /api/documentation/routes
 * Get all API routes with their methods and categories
 */
router.get('/routes', async (req, res) => {
  try {
    const routes = await DocumentationService.getApiRoutes();
    res.json(routes);
  } catch (error) {
    logger.error('Error getting API routes:', error);
    res.status(500).json({
      success: false,
      error: 'Failed to get API routes',
      message: error.message
    });
  }
});

/**
 * GET /api/documentation/data-flows
 * Get actual data flow configurations
 */
router.get('/data-flows', async (req, res) => {
  try {
    const flows = await DocumentationService.getDataFlows();
    res.json(flows);
  } catch (error) {
    logger.error('Error getting data flows:', error);
    res.status(500).json({
      success: false,
      error: 'Failed to get data flows',
      message: error.message
    });
  }
});

/**
 * GET /api/documentation/modules
 * Get module implementation status
 */
router.get('/modules', async (req, res) => {
  try {
    const modules = await DocumentationService.getModuleStatus();
    res.json(modules);
  } catch (error) {
    logger.error('Error getting module status:', error);
    res.status(500).json({
      success: false,
      error: 'Failed to get module status',
      message: error.message
    });
  }
});

/**
 * GET /api/documentation/health
 * Health check for documentation service
 */
router.get('/health', (req, res) => {
  res.json({
    success: true,
    service: 'DocumentationService',
    status: 'healthy',
    timestamp: new Date().toISOString()
  });
});

module.exports = router;
